formSecret: secretValueForGeneratingCSRFTokens
sharedPassword: password
adminPassword: password
enforceHttps: false
emails:
  - notify@example.com
database:
  driver: pdo_sqlite
  path: migrations/applicants.sqlite
  user: root
  password:
  host: 127.0.0.1