formSecret: secretValueForGeneratingCSRFTokens
sharedPassword: password
adminPassword: password
enforceHttps: false
emails:
  - me@mylesbraithwaite.com
database:
  driver: pdo_mysql
  dbname: hacklab_to_apply
  user: root
  password:
  host: 127.0.0.1